# -*- mode: ruby -*-
# vi: set ft=ruby :

#Machine Client 2

Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian11"
  
  config.vm.hostname = "client2"
  # mettre deux IP différentes à la place de XX sur serveur et client:
  #config.vm.network "private_network", type: "static", ip: "192.168.56.10"
  config.vm.network "public_network", bridge: "enp0s3", ip: "192.168.1.11"
  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
  SHELL
end
